version: '3.7'
services:
  app:
    image: ignite-lab/node-notification-app
    container_name: ignite-lab-node-notification-app
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:13-alpine3.17
    container_name: ignite-lab-node-notification-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: notification
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
