version: '3.7'
services:
  app:
    image: ignite-lab-node-notification-app-dev
    container_name: ignite-lab-node-notification-app-dev
    hostname: docker
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
      args:
        USERNAME: ${USER}
    volumes:
      - ..:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: /bin/bash -c "yarn start:debug"

  db:
    image: postgres:13-alpine3.17
    container_name: ignite-lab-node-notification-db-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: notification
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
