FROM node:18-slim

ARG USERNAME=userapp
ARG USER_UID=9999
ARG USER_GID=$USER_UID

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

RUN groupadd --gid $USER_GID $USERNAME && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME

RUN apt-get update && apt-get install apt-utils && apt-get upgrade -y && apt-get dist-upgrade -y && apt-get autoremove -y && \
  apt-get install -y \
  curl \
  fonts-jetbrains-mono \
  git \
  htop \
  nano \
  net-tools \
  procps \
  sudo \
  wget \
  zsh

RUN echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME && chmod 0440 /etc/sudoers.d/$USERNAME

USER $USERNAME

RUN sudo su $USERNAME && sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
RUN git clone https://github.com/zsh-users/zsh-syntax-highlighting.git /home/$USERNAME/.oh-my-zsh/plugins/zsh-syntax-highlighting
RUN sed -i 's/plugins=(git)/plugins=(command-not-found git git-flow history npm yarn zsh-syntax-highlighting)/g' /home/$USERNAME/.zshrc
RUN sed -i 's/ZSH_THEME="robbyrussell"/ZSH_THEME="bira"/g' /home/$USERNAME/.zshrc

RUN sudo chsh -s /bin/zsh $USERNAME

RUN npm config set loglevel=error update-notifier=false && sudo npm config set loglevel=error update-notifier=false

CMD ["sleep", "infinity"]
